server:
  port: 7003
  
eureka:
  instance:
    hostname: eureka-7003.com         # 添加hosts解析：127.0.0.1 eureka-7003.com
  client:
    register-with-eureka: false       # false 表示不向注册中心注册自己
    fetch-registry: false             # false 表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:                      # 设置与Eureka Server交互的地址查询服务和注册服务
      defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/