spring:
  datasource:
# 数据源基本配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: spring_boot
    password: 123456
    schema:
      - classpath:sql/schema-department.sql         # 指定sql文件的位置
      - classpath:sql/schema-employee.sql
    type: com.alibaba.druid.pool.DruidDataSource    # 指定数据源
# 数据源其他配置
    validation-query: SELECT 1
    initial-size: 2
    min-idle: 2
    max-active: 8
    max-wait: 60000
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat, wall, log4j
    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis 配置文件所在路径
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml               # mapper 映射文件
    
logging:
  level:
    cn.colg.mapper: debug