server:
  port: 8001
  
person:
  last-name: Jack
  age: 18
  boss: false
  birth: 2017/12/12
  maps:
    k1: v1
    k2: v2
  lists:
    - Jack
    - Rose
  dog:
    name: 小狗
    age: 3
    
cat:
  lastName: black
  age: 3
  birth: 2018/03/15

taxi:
  name: 丰田卡罗拉${random.uuid}
  plate-number: 鄂FPN18${random.int[10]}
  age: ${random.int[1,3]}
  dog:
    name: ${taxi.hello:小狗}
    age: ${taxi.age}