server:
  port: 8001
  
spring:
  profiles:
    include:
      - mybatis                                           # 激活配置文件
  application:
    name: spring-cloud-dept                               # 应用名称（对外暴露的微服务名称）
    
logging:
  level:
    cn.colg.dao: debug