server:
  port: 80
  
eureka:
  client:
    register-with-eureka: false                 # false 表示不向注册中心注册自己
    service-url:                                # 将客户端注册进eureka服务列表内
      defaultZone: http://eureka-7001.com:7001/eureka/,http://eureka-7002.com:7002/eureka/,http://eureka-7003.com:7003/eureka/